#!/bin/bash
#
# Input JSON from STDIN
# {
#   "params": {
#     "remotedir": "/test/"
#   },
#   "source": {
#     "url": "https://download.opensuse.org",
#     "regexp": "file-(.*).ext"
#   }
# }

set -e
IFS=" "

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

payload=$(mktemp /tmp/resource-in.XXXXXX)
cat > $payload <&0

parse_source_config

source=$1

if [ -z "$source" ]; then
  echo "usage: $0 <path/to/source>"
  exit 1
fi

remotedir=$(jq -r '.params.remotedir // ""' < $payload)

cd $source
echo "Uploading files to remote/$remotedir."
if [ ! -z "$remotedir" ]; then
  lftp -c "set sftp:auto-confirm yes; open $URL; mkdir -p $remotedir; cd $remotedir; mirror -R"
else
  lftp -c "set sftp:auto-confirm yes; open $URL; mirror -R"
fi

# The script must emit the resulting version of the resource.
get_listing
parse_versions
VERSION=$(echo $FOUND_VERSIONS | sort -rh | head -1)
cat >&3 <<EOF
{
  "version": { "ref": "$VERSION" }
}
EOF
